### ISSUE TITLE
What version of font awesome are you using ?

### ISSUE THREAD

**Issue by brunetton** [UtkarshVerma/i3blocklets#2]
I'm playing around with your scripts, but some glyphs are not displaying correctely (for example: disk usage). I'm using Font Awesome v4.7.0
What version of Font Awesome are you using ? 

Thanks

**Comment by UtkarshVerma** [comment]
@brunetton I have v4.7.0 as well, therefore the glyphs should be displayed. Did you specify the font to i3bar in the [config](https://github.com/UtkarshVerma/dotfiles/blob/master/i3/config#L189)? I can't think of anything else.
